### ISSUE TITLE
Config file fails to install

### ISSUE THREAD

**Issue by Ruestir** [DelilahEve/ValheimPatcher#2]
Installer works up until installing configs and then errors out with "Config files failed to install: InvalidDataException
[ValheimPatcherError_202202031435343092.zip](https://github.com/DelilahEve/ValheimPatcher/files/7997632/ValheimPatcherError_202202031435343092.zip)
"

**Comment by DelilahEve** [comment]
After investigation I've learned this is related to a config zip for my easy QoL modpack that no longer exists, I'll likely have to declare that pack dead as I lost the config files it seems.
