### ISSUE TITLE
Darkheim 3.0 Crashes on load

### ISSUE THREAD

**Issue by JellyJamBoy** [DelilahEve/ValheimPatcher#3]
Hi DelilahEve,

I'm using the Darkheim 3.0 modpack for my Youtube playthrough and I left it for a few weeks, reinstalled Valheim and reinstalled the modpack and it now crashes on load up :( Is the modpack still viable?

Thanks for your help,

Jelly
YT series using the modpack in case you're curious: https://www.youtube.com/watch?v=VLur032EWJk

**Comment by DelilahEve** [comment]
TimoRedbeard is the maintainer of that pack, he would have to say if it's broken or not. The default packs are maintained in a separate repo: https://github.com/DelilahEve/ValheimPatcherConfig 

It would be best to tag him with an issue over there, though I don't know what his response time will be.

Alternately the pack is open source and you're welcome to submit fixes at any time should you find the source of the issue.
